### ISSUE TITLE
Some questions about training time

### ISSUE THREAD

**Issue by XYTriste** [alirezakazemipour/PPO-RND#2]
Hello, I am a student from China. I am currently trying to train using the PPO+RND algorithm under Montezuma's revenge. I have referred to various open source code settings online for the setting of hyperparameters. But after 10 hours of training (about 6 million frames), the  agent still couldn't even find the key to the first room. How long did it take for you to train the effect you posted on the homepage? I understand that this is an extremely difficult environment to explore for rewards, but the lack of effectiveness has also made me feel very frustrated. Thank you very much for your reply.

**Comment by akazemipour** [comment]
Hi there,
Thank you very much for your question and also, finding my code potentially useful! *_*
Does my code also take so much time with nothing happening?
I remember the time to make progress in the game was directly proportional to the number of parallel workers so, how many parallel workers do you use?
Off the top of my head, I recall with 128 workers, it took less than 3 hours to have the agent make it to the second room.

**Comment by XYTriste** [comment]
well...Prior to this, I only attempted to use some of the hyperparameters and general settings provided in your code, because as a student, I would prefer to be able to implement this algorithm myself Or at least let me know where I made a mistake.
But before training in this environment, I also used the code I implemented on other Atari games for training, and although I did not converge to the optimal solution, I also achieved good results.
As for the 'parallel workers' you mentioned, I thought you were referring to the number of parallel threads during the training process, but when I realized that you were referring to' recall with 128 workers', I realized that there may be a problem with my understanding. I used 8 threads, each with a agent, and they shared a model for training. If according to what you said, my code may only be '8 workers', perhaps my code implementation is not a problem It's just that the efficiency is too low.
I will refer to your implementation to make adjustments to my code. Thank you for your help with open source code and for your enthusiastic and timely response.

**Comment by XYTriste** [comment]
Wait, after referencing your code. It seems that my understanding of 'parallel workers' is not wrong. But this still makes me feel a bit confused, because in my understanding, it seems that the number of threads should not exceed the number of cores in the CPU. For example, my CPU model is Intel i7-12700k, which is a 12 core 20 thread CPU. Will using 128 threads for training not cause the CPU to frequently switch between threads and reduce efficiency? Perhaps I should also tutoring my operating system knowledge...

**Comment by akazemipour** [comment]
Yes, your understanding is completely correct!
You either have to have a more powerful machine or to sacrifice the efficiency.
With less than 32 workers, it’s hard to get any practical results.
